name: "PR diff bot"
on: [pull_request]
permissions: read-all

jobs:
  build:
    name: PR diff bot
    runs-on: ubuntu-latest
    steps:
      - name: Setup node
        uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1.4.6
        with:
          node-version: 18.x

      - name: Checkout base branch
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
        with:
          ref: ${{ github.base_ref }}

      - name: Record before stats
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          mkdir .diff
          npm ci
          npm run build
          cat packages/browser/dist/bugsnag.min.js | wc -c > .diff/size-before-minified
          cat packages/browser/dist/bugsnag.min.js | gzip | wc -c > .diff/size-before-gzipped

      - name: Checkout PR branch
        uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1.2.0
        with:
          clean: false

      - name: Record after stats
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: |
          npm ci
          npm run build
          cat packages/browser/dist/bugsnag.min.js | wc -c > .diff/size-after-minified
          cat packages/browser/dist/bugsnag.min.js | gzip | wc -c > .diff/size-after-gzipped

      - name: Run danger
        uses: danger/danger-js@92d2525fe338bff16ae7d42794d0a835e2d27473 # 12.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
